title={{short_desc}}
authoremail={{email}}
variables=-V title:"$(title)" -V client:"$(client)" -Vauthoremail:$(authoremail) -V document-sha:$(document-sha) -V status:"$(docstatus)"
files={{project_name}}.md
input=in.md
default:mkpdf
mklib:
	antlr4 -Dlanguage=Python3 grammar/{{project_name}}.g4 -o src/{{project_name}}
$(files): mklib
	{{project_name}} {{project_name}} $(input) ${{project_name}}.md
mkpdf: $(files)
	pandoc --toc --from=markdown+lists_without_preceding_blankline  -F pandoc-imagine $(variables) -o reference_manual.pdf -s --template=$(HOME)/.pandoc/template/dyu/refman.template $(files) 
